"""Genuine (if compact) domain Q&A corpora for training the med/law adapters.
Generic educational content only -- no real patient/case data."""

MED_QA = [
    ("What are the common symptoms of type 2 diabetes?", "Common symptoms include increased thirst, frequent urination, fatigue, blurred vision, and slow-healing wounds."),
    ("What causes hypertension?", "Hypertension can be caused by genetics, high salt intake, obesity, lack of physical activity, chronic stress, and kidney disease."),
    ("How is pneumonia diagnosed?", "Pneumonia is diagnosed through physical examination, chest X-ray, blood tests, and sometimes sputum culture."),
    ("What is the normal range for resting heart rate?", "A normal resting heart rate for adults ranges from 60 to 100 beats per minute."),
    ("What are the first-line treatments for migraine?", "First-line treatments include NSAIDs, triptans, rest in a dark quiet room, and hydration."),
    ("What is atrial fibrillation?", "Atrial fibrillation is an irregular and often rapid heart rhythm originating in the atria, increasing stroke risk."),
    ("How does insulin regulate blood sugar?", "Insulin allows cells to absorb glucose from the bloodstream, lowering blood sugar levels after eating."),
    ("What are the warning signs of a stroke?", "Warning signs include sudden numbness, confusion, trouble speaking, vision problems, and loss of balance."),
    ("What is the function of the liver?", "The liver metabolizes nutrients, filters toxins from blood, produces bile, and synthesizes proteins."),
    ("What causes iron-deficiency anemia?", "It is caused by insufficient iron intake, blood loss, or poor iron absorption, leading to reduced hemoglobin production."),
    ("What is the recommended treatment for a mild concussion?", "Rest, avoiding screens and strenuous activity, and gradual return to normal activity under medical supervision."),
    ("What are the symptoms of appendicitis?", "Symptoms include abdominal pain starting near the navel and moving to the lower right side, nausea, fever, and loss of appetite."),
    ("How is asthma managed?", "Asthma is managed with inhaled corticosteroids, bronchodilators, avoiding triggers, and an action plan for flare-ups."),
    ("What is the difference between Type 1 and Type 2 diabetes?", "Type 1 is an autoimmune condition with little to no insulin production; Type 2 involves insulin resistance, often related to lifestyle factors."),
    ("What is the purpose of a colonoscopy?", "A colonoscopy examines the colon for polyps, cancer, inflammation, and other abnormalities."),
    ("What are common side effects of antibiotics?", "Common side effects include nausea, diarrhea, allergic reactions, and disruption of gut flora."),
    ("What is hypothyroidism?", "Hypothyroidism is a condition where the thyroid gland does not produce enough thyroid hormone, causing fatigue and weight gain."),
    ("How is a fever typically treated at home?", "Rest, fluids, and over-the-counter antipyretics like acetaminophen or ibuprofen are typical home treatments."),
    ("What are risk factors for coronary artery disease?", "Risk factors include smoking, high cholesterol, hypertension, diabetes, obesity, and family history."),
    ("What is the purpose of a vaccine?", "Vaccines stimulate the immune system to recognize and fight specific pathogens without causing the disease itself."),
    ("What is chronic obstructive pulmonary disease (COPD)?", "COPD is a progressive lung disease causing airflow blockage, often caused by long-term smoking."),
    ("What are symptoms of a urinary tract infection?", "Symptoms include burning during urination, frequent urge to urinate, cloudy urine, and pelvic pain."),
    ("How does the body regulate temperature?", "The hypothalamus regulates body temperature through sweating, shivering, and adjusting blood flow to the skin."),
    ("What is the role of white blood cells?", "White blood cells are part of the immune system and help the body fight infections and foreign invaders."),
    ("What causes osteoporosis?", "Osteoporosis is caused by loss of bone density, often due to aging, hormonal changes, or calcium/vitamin D deficiency."),
    ("What is the difference between a virus and a bacterium?", "Viruses require a host cell to replicate, while bacteria are single-celled organisms that can reproduce independently."),
    ("What are symptoms of dehydration?", "Symptoms include dry mouth, dizziness, dark urine, fatigue, and reduced urine output."),
    ("What is the purpose of an MRI scan?", "An MRI uses magnetic fields to produce detailed images of organs and tissues without radiation exposure."),
    ("What lifestyle changes help manage high cholesterol?", "A low-saturated-fat diet, regular exercise, weight management, and avoiding smoking help manage cholesterol."),
    ("What is anaphylaxis?", "Anaphylaxis is a severe, life-threatening allergic reaction requiring immediate treatment with epinephrine."),
]

LAW_QA = [
    ("What is the difference between civil and criminal law?", "Civil law resolves disputes between private parties, while criminal law addresses offenses against the state or public order."),
    ("What is a contract?", "A contract is a legally binding agreement between two or more parties that creates enforceable obligations."),
    ("What are the essential elements of a valid contract?", "The essential elements are offer, acceptance, consideration, capacity, and mutual intent to be bound."),
    ("What is negligence in tort law?", "Negligence is the failure to exercise reasonable care, resulting in harm to another person."),
    ("What is the statute of limitations?", "The statute of limitations is the maximum time period allowed to initiate legal proceedings after an event occurs."),
    ("What is intellectual property?", "Intellectual property refers to legal rights over creations of the mind, including patents, trademarks, and copyrights."),
    ("What is the purpose of a will?", "A will is a legal document that specifies how a person's assets should be distributed after their death."),
    ("What is habeas corpus?", "Habeas corpus is a legal principle that protects individuals from unlawful detention by requiring justification before a court."),
    ("What is the difference between a misdemeanor and a felony?", "A misdemeanor is a less serious crime with lighter penalties, while a felony is a more serious crime carrying harsher punishment."),
    ("What is due process?", "Due process is the legal requirement that the state must respect all legal rights owed to a person, ensuring fair treatment."),
    ("What is breach of contract?", "A breach of contract occurs when one party fails to fulfill their obligations under the agreement without lawful excuse."),
    ("What is the role of precedent in common law?", "Precedent, or stare decisis, requires courts to follow rulings from prior similar cases to ensure consistency in the law."),
    ("What is a tort?", "A tort is a civil wrong that causes harm or loss, giving the injured party the right to seek compensation."),
    ("What is the burden of proof in a criminal case?", "In criminal cases, the prosecution must prove guilt beyond a reasonable doubt."),
    ("What is a power of attorney?", "A power of attorney is a legal document granting one person the authority to act on behalf of another in legal or financial matters."),
    ("What is defamation?", "Defamation is a false statement presented as fact that harms a person's reputation, divided into libel and slander."),
    ("What is the purpose of a non-disclosure agreement?", "An NDA legally binds parties to keep specified information confidential and not disclose it to third parties."),
    ("What is jurisdiction?", "Jurisdiction is the official authority of a court to hear and decide legal cases within a defined geographic or subject-matter scope."),
    ("What is the difference between a plaintiff and a defendant?", "The plaintiff is the party who initiates a lawsuit, while the defendant is the party being sued or accused."),
    ("What is arbitration?", "Arbitration is a method of resolving disputes outside of court, where an impartial arbitrator renders a binding decision."),
    ("What is force majeure in contract law?", "Force majeure is a clause that excuses parties from contractual obligations due to extraordinary events beyond their control."),
    ("What is the concept of vicarious liability?", "Vicarious liability holds one party legally responsible for the wrongful acts of another, typically an employer for an employee."),
    ("What is a class action lawsuit?", "A class action lawsuit allows a group of people with similar claims against a defendant to sue collectively."),
    ("What is the difference between mediation and litigation?", "Mediation is a voluntary, informal process to reach a settlement, while litigation is a formal court process resolved by a judge or jury."),
    ("What are damages in a civil lawsuit?", "Damages are monetary compensation awarded to a plaintiff for loss or injury caused by the defendant's actions."),
    ("What is a fiduciary duty?", "A fiduciary duty is a legal obligation to act in the best interest of another party, such as a trustee for a beneficiary."),
    ("What is the purpose of a trademark?", "A trademark protects brand names, logos, and symbols used to identify goods or services from a specific source."),
    ("What is an injunction?", "An injunction is a court order requiring a party to do or refrain from doing a specific act."),
    ("What is the concept of double jeopardy?", "Double jeopardy prevents a person from being tried twice for the same offense after acquittal or conviction."),
    ("What is a legal precedent?", "A legal precedent is a prior court decision that serves as an authoritative example for deciding future similar cases."),
]
